# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4119852d09340a07be657308ae7dd7c82fc6c0ba54b9cad90112dbcb386dda01aefec0cf57c48310efb4c84d15c432e3383015462c98cf56348cf07008e78b1

test:
  secret_key_base: b7a62edf98b6cf9fd678736babbcb52dee74e16973445d5a47793aa7d263ee56bcfaa17259cff9fcaccc718d09818be032e3e241e3ebbf32f72c781d037e5656

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
